### ISSUE TITLE
Flow label problem

### ISSUE THREAD

**Issue by felipeRomano92** [GetMati/mati-ios-sdk#16]
Hi!
The reason for my message is because I have some problems integrating the Mati flow into my application.
When I am inside the Mati flow, the labels look bad. (the texts they present are incorrect).

![Image_20210721_164915](https://user-images.githubusercontent.com/87784888/126564986-1e0fd16a-e74b-4749-a650-4d75accc73ad.png)

![Image_20210721_164921](https://user-images.githubusercontent.com/87784888/126564997-83d9229e-7c49-4a25-a920-10d42fdc19a3.png)

There is my code in VC

`
import UIKit
import MatiSDK

class HelpViewController: MenuOptionViewController,HelpViewControllerProtocol {
    
    ///Funcion para asignar titulo de la vista
    override func persistaintTitle() -> String? {"Help".localized()}
    
    //--------------------------------------------------------------------------
    //MARK: - Outlets
    //--------------------------------------------------------------------------
    
    @IBOutlet weak var mButton: UIButton!
    
    
    //--------------------------------------------------------------------------
    //MARK: - Properties
    //--------------------------------------------------------------------------
    var presenter: HelpPresenterProtocol?
    
    //--------------------------------------------------------------------------
    //MARK: - Functions
    //--------------------------------------------------------------------------
    override func viewDidLoad() {
        self.initMati()
    }
    func initMati(){
        
        MatiButtonResult.shared.delegate = self
    }
    
    @IBAction func matiAction(_ sender: Any) {
      //set params to showMatiFlow
        MatiSDK.shared.showMatiFlow(clientId: "60ed92a973d6da001b96fbd0",
                    flowId: "60eef0d773d6da001ba393cf",
                    metadata: ["id": "8001"])
    }
    
`

`

extension HelpViewController: MatiButtonResultDelegate{

    func verificationSuccess(identityId: String) {

        print(identityId)

    }

    func verificationCancelled() {

        print("Cancelado")

      }

    }
`

This is my Info.plis

`<key>NSCameraUsageDescription</key>

	<string>Accept camera permissions to take photos of your car</string>

	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>

	<string>Accept geolocation permissions to receive offers and perform custom searches.</string>

	<key>NSLocationAlwaysUsageDescription</key>

	<string>Accept geolocation permissions to receive offers and perform custom searches.</string>

	<key>NSLocationWhenInUseUsageDescription</key>

	<string>Accept geolocation permissions to receive offers and perform custom searches.</string>

	<key>NSMicrophoneUsageDescription</key>

	<string>Beepy needs access to your Microphone</string>

	<key>NSPhotoLibraryUsageDescription</key>

	<string>Beepy needs access to your media library</string>`

This is my console 

<img width="2560" alt="Captura de Pantalla 2021-07-21 a la(s) 18 34 28" src="https://user-images.githubusercontent.com/87784888/126572752-78ec534d-0664-4467-bb24-864ffe6da682.png">

For us it is important to be able to integrate Mati as soon as possible into our iOS app, so we hope you can support us.
I’m awaiting your reply. 
Have a nice day!

**Comment by aposnovmati** [comment]
Hello @felipeRomano92 thanks a lot for detail issues, i have one question before take it to investigation, did you try to re install pod? and fully remove it by "pod clean" command?

**Comment by felipeRomano92** [comment]
Hi! @aposnovmati !
I already try this recommendations.
We assume, that our string file conflicts with yours.
Since on another occasion we have had to rename methods since we use the same name.

**Comment by aposnovmati** [comment]
Hello @felipeRomano92 1) could you send example of rename methods? maybe we should rename ours to unique and avoid situation in future 2) do you have methods as extensions of Strings named "localized" ?

**Comment by felipeRomano92** [comment]
Hello @aposnovmati 
1) There is an example 
```
@objc public func dismissKeyboard2() 
{
  endEditing(true)
}
```
2) yes, we do
```
extension String {

  func localized(comment: String? = nil) -> String{
        return NSLocalizedString(self, comment: comment ?? self)
    }

}

```

**Comment by aposnovmati** [comment]
Okay thats the problem with localized, could you rename it temporary? we will change it next version

**Comment by felipeRomano92** [comment]
Hello @aposnovmati 
I renamed the method, remove and re install the pod, but the problem. is still there :(

**Comment by aposnovmati** [comment]
let me prepare a fix on Monday (26 July) @felipeRomano92 to rename our methods

**Comment by aposnovmati** [comment]
@felipeRomano92  Hello, sorry for delay, we plan to release it tomorrow (4 aug)

**Comment by aposnovmati** [comment]
Hello @felipeRomano92 we have just released new version iOS SDK 3.3.0 could you try it please?

**Comment by felipeRomano92** [comment]
Hello @aposnovmati 
Thanks a lot! 
let me try and I will notify you if the problem of the labels is resolved.

**Comment by felipeRomano92** [comment]
Hi @aposnovmati !
I am afraid that the new version does not solve the error with the labels.
I enclose evidence that I have successfully loaded the new version.


<img width="518" alt="Captura de Pantalla 2021-08-05 a la(s) 11 09 23" src="https://user-images.githubusercontent.com/87784888/128384940-067dbbc0-7e26-455d-9cb3-5fa24fba58c8.png">

![Image_20210805_111142](https://user-images.githubusercontent.com/87784888/128384999-8140d46a-6e67-4d86-8e6a-64f0e0bc723e.png)

![Image_20210805_111145](https://user-images.githubusercontent.com/87784888/128385027-86686b5a-f70f-4359-8bc7-8aa0a6d86c74.png)

**Comment by aposnovmati** [comment]
thank @felipeRomano92 let me prepare one more version

**Comment by aposnovmati** [comment]
@felipeRomano92 please try the new 3.3.1 version, i will wait for feedback

**Comment by felipeRomano92** [comment]
Let me try

**Comment by felipeRomano92** [comment]
I have a new error
![image](https://user-images.githubusercontent.com/87784888/128393652-d43547e4-a8e3-4ef9-aef9-427282d2ef07.png)

**Comment by aposnovmati** [comment]
@felipeRomano92 sorry, my bad, we changed MatiSDK.shared.showMatiFlow changed to Mati.shared.showMatiFlow (MatiSDK to Mati) please try it

**Comment by felipeRomano92** [comment]
@aposnovmati sorry, the problem is still present

**Comment by aposnovmati** [comment]
@felipeRomano92 did you use “pod clean” to fully remove library, and pod install again? If yes, could we have online call tomorrow? To try resolve it online?

**Comment by aposnovmati** [comment]
@felipeRomano92 could you please try 3.3.2 version? we have just published

**Comment by felipeRomano92** [comment]
yes, let me try, about the online call, I am asking my superiors to plan the time well

**Comment by felipeRomano92** [comment]
sorry..  the problem is still present

**Comment by felipeRomano92** [comment]
Hi @aposnovmati !!
Could we make the call tomorrow at 8am from Mexico City?

**Comment by aposnovmati** [comment]
Hello @felipeRomano92 yes, lets shedule this time tomorrow 10 aug, could you write me to email andrey.posnov@mati.io

**Comment by aposnovmati** [comment]
Hello, the problem was on the client-side by using swizzleLocalization method, details here https://dev.to/eldare/forcing-ios-localization-at-runtime-the-right-way-2o24 , and this problem mentioned there too. 

If you will have new questions/issues, please open a new ticket
